# Generated by Django 4.2.13 on 2025-04-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('seats', models.PositiveIntegerField(default=0, verbose_name='Количество мест')),
                ('location', models.CharField(choices=[('indoor', 'В помещении'), ('outdoor', 'На улице'), ('window', 'У окошка'), ('nearexit', 'У выхода')], max_length=255, verbose_name='Местонахождение')),
                ('busyness', models.BooleanField(default=False, verbose_name='Занятость')),
            ],
            options={
                'verbose_name': 'Столик',
                'verbose_name_plural': 'Столики',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Имя заказчика')),
                ('reservation_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.tables')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
